### ISSUE TITLE
Handle variables in help text

### ISSUE THREAD

**Issue by Zoidmania** [taskipy/taskipy#77]
I'd like to do something like this:

```toml
[tool.taskipy.settings]
use_vars = true

[tool.taskipy.variables]
some_var = "foo"

[tool.taskipy.tasks]
baz = { cmd="echo '{some_var}'", help = "Do something like {some_var}." }
```

However, variables aren't handled in help text, unlike in commands:

```bash
$ task -l
baz    Do something like {some_var}.

$ task baz
foo
```
